
GET http://localhost:3001/api/patients


###
POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name" : "John Doe",
    "dateOfBirth" : "1998-5-20",
    "gender" : "female",
    "occupation" : "doctor"
}